# Generated by Django 3.1.2 on 2020-11-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20201112_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='имя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('image', models.ImageField(upload_to='static/message_image')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_image', to='message.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
