# Generated by Django 3.1.2 on 2020-11-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_messageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='messageimage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='messageimage',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='messageimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='messageimage',
            name='updated',
        ),
    ]
