# Generated by Django 3.2.6 on 2021-08-29 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(default='DEFAULT VALUE', max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='123.jpg', null=True, upload_to='')),
                ('bio', models.TextField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relationship', models.CharField(choices=[('None selected', 'None selected'), ('Unmarried', 'Unmarried'), ('In a relationship', 'In a relationship'), ('Engaged', 'Engaged'), ('Married', 'Married'), ('In a civil union', 'In a civil union'), ('In love', 'In love'), ('Its complicated', 'Its complicated '), ('Actively searching', 'Actively searching')], max_length=200, null=True, verbose_name='Relationship')),
                ('families', models.CharField(blank=True, choices=[('Grandparents', 'Grandparents'), ('Parents', 'Parents'), ('Siblings', 'Siblings'), ('Children', 'Children'), ('Grandchildren', 'Grandchildren')], max_length=255, null=True, verbose_name='Family')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], max_length=200, null=True, verbose_name='Gender')),
                ('bday', models.DateField(null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='personal_skills', to='core.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
