# Generated by Django 4.0 on 2022-01-22 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('bday', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(default='123.jpg', null=True, upload_to='profile', verbose_name='Profile photo')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], max_length=200, null=True, verbose_name='Gender')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution ')),
                ('relationship', models.CharField(choices=[('None selected', 'None selected'), ('Unmarried', 'Unmarried'), ('In a relationship', 'In a relationship'), ('Engaged', 'Engaged'), ('Married', 'Married'), ('In a civil union', 'In a civil union'), ('In love', 'In love'), ('Its complicated', 'Its complicated '), ('Actively searching', 'Actively searching')], max_length=200, null=True, verbose_name='Relationship')),
                ('families', models.CharField(blank=True, choices=[('Grandparents', 'Grandparents'), ('Parents', 'Parents'), ('Siblings', 'Siblings'), ('Children', 'Children'), ('Grandchildren', 'Grandchildren')], max_length=255, null=True, verbose_name='Family')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
