# Generated by Django 3.2.6 on 2021-08-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
