# Generated by Django 3.1.2 on 2020-10-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
