# Generated by Django 3.2.6 on 2021-09-05 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_related_name': 'profile', 'verbose_name': 'profile'},
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='123.jpg', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
