# Generated by Django 3.2.6 on 2021-09-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210905_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicTag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
