# Generated by Django 3.1.2 on 2020-10-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201012_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
