# Generated by Django 3.1.2 on 2020-10-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201014_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/default-profile.jpg', upload_to='profiles'),
        ),
    ]
