# Generated by Django 3.2.6 on 2021-09-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
