# Generated by Django 3.1.2 on 2020-10-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201014_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='named',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
