# Generated by Django 3.1.2 on 2020-10-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201014_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='named',
            new_name='surname',
        ),
    ]
