# Generated by Django 3.2.6 on 2021-09-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
