# Generated by Django 3.1.2 on 2020-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201014_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
