# Generated by Django 3.1.2 on 2020-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201015_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Institution',
            field=models.TextField(blank=True, max_length=355, null=True, verbose_name='institution'),
        ),
    ]
