# Generated by Django 3.1.2 on 2020-10-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_profile_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Institution',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='institution'),
        ),
    ]
