# Generated by Django 3.1.2 on 2020-10-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201015_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Institution',
            new_name='institution',
        ),
    ]
