# Generated by Django 3.1.2 on 2020-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201015_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[('N', 'None selected'), ('U', 'Unmarried'), ('I', 'In a relationship'), ('E', 'Engaged'), ('M', 'Married'), ('C', 'In a civil union'), ('L', 'In love'), ('S', 'Its complicated '), ('A', 'Actively searching')], max_length=200, null=True),
        ),
    ]
