# Generated by Django 3.1.2 on 2020-10-20 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='families',
            field=models.ManyToManyField(blank=True, choices=[('G', 'Grandparents'), ('P', 'Parents'), ('S', 'Siblings'), ('C', 'Children'), ('D', 'Grandchildren')], related_name='family', to=settings.AUTH_USER_MODEL, verbose_name='Семья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], max_length=200, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[('N', 'None selected'), ('U', 'Unmarried'), ('I', 'In a relationship'), ('E', 'Engaged'), ('M', 'Married'), ('C', 'In a civil union'), ('L', 'In love'), ('S', 'Its complicated '), ('A', 'Actively searching')], max_length=200, null=True, verbose_name='Отношения'),
        ),
    ]
