# Generated by Django 3.1.2 on 2020-10-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201020_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='families',
        ),
        migrations.AddField(
            model_name='profile',
            name='families',
            field=models.CharField(choices=[('G', 'Grandparents'), ('P', 'Parents'), ('S', 'Siblings'), ('C', 'Children'), ('D', 'Grandchildren')], max_length=255, null=True, verbose_name='Семья'),
        ),
    ]
