# Generated by Django 3.1.2 on 2020-10-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201023_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/default-profile.jpg', null=True, upload_to='media', verbose_name='Фото профиля'),
        ),
    ]
