# Generated by Django 3.1.2 on 2020-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201025_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to=''),
        ),
    ]
