# Generated by Django 3.1.2 on 2020-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20201025_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default-profile.jpg', null=True, upload_to='static/images', verbose_name='Фото профиля'),
        ),
    ]
