# Generated by Django 3.1.2 on 2020-10-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20201028_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='mail',
        ),
    ]
