# Generated by Django 3.1.2 on 2020-10-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20201028_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail',
            new_name='email',
        ),
    ]
