# Generated by Django 3.1.2 on 2020-10-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='mail',
        ),
    ]
