# Generated by Django 3.1.2 on 2020-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20201029_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(max_length=255, null=True, verbose_name='Электронная почта'),
        ),
    ]
