# Generated by Django 3.1.2 on 2020-11-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to='core.Profile', verbose_name='Подписка'),
        ),
    ]
