# Generated by Django 3.1.2 on 2020-11-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20201103_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
