# Generated by Django 3.1.2 on 2020-11-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20201103_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
