# Generated by Django 3.1.2 on 2020-11-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20201103_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
