# Generated by Django 3.1.2 on 2020-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20201112_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=False, max_length=255, verbose_name='имя'),
        ),
    ]
