# Generated by Django 3.1.3 on 2020-11-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20201116_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='families',
            field=models.CharField(blank=True, choices=[('Grandparents', 'Grandparents'), ('Parents', 'Parents'), ('Siblings', 'Siblings'), ('Children', 'Children'), ('Grandchildren', 'Grandchildren')], max_length=255, null=True, verbose_name='Семья'),
        ),
    ]
