# Generated by Django 3.1.2 on 2020-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20201114_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[('None selected', 'None selected'), ('Unmarried', 'Unmarried'), ('In a relationship', 'In a relationship'), ('Engaged', 'Engaged'), ('Married', 'Married'), ('In a civil union', 'In a civil union'), ('In love', 'In love'), ('Its complicated', 'Its complicated '), ('Actively searching', 'Actively searching')], max_length=200, null=True, verbose_name='Отношения'),
        ),
    ]
