# Generated by Django 3.1.3 on 2020-11-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20201115_1949'),
        ('core', '0076_auto_20201114_0059'),
        ('core', '0077_auto_20201119_1758'),
    ]

    operations = [
    ]
