# Generated by Django 3.1.3 on 2020-11-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20201120_1223'),
        ('core', '0079_auto_20201119_1821'),
    ]

    operations = [
    ]
