# Generated by Django 3.1.3 on 2020-11-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20201119_1856'),
        ('core', '0082_merge_20201122_1106'),
    ]

    operations = [
    ]
