# Generated by Django 3.1.3 on 2020-11-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20201124_1914'),
        ('core', '0079_auto_20201119_1856'),
    ]

    operations = [
    ]
