# Generated by Django 3.1.3 on 2020-11-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_merge_20201125_1623'),
        ('core', '0078_auto_20201121_1410'),
    ]

    operations = [
    ]
