# Generated by Django 3.1.3 on 2021-07-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_merge_20201126_1842'),
        ('core', '0085_merge_20201125_1700'),
    ]

    operations = [
    ]
