# Generated by Django 3.1.3 on 2021-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20210730_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/123.jpg', null=True, upload_to='', verbose_name='Profile photo'),
        ),
    ]
