# Generated by Django 3.1.3 on 2021-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20210730_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='123.jpg', null=True, upload_to='profile', verbose_name='Profile photo'),
        ),
    ]
