# Generated by Django 3.1.3 on 2020-11-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_item',
            name='album',
        ),
        migrations.AddField(
            model_name='gallery_item',
            name='album',
            field=models.ManyToManyField(related_name='album', to='gallery.Album', verbose_name='альбом'),
        ),
    ]
