# Generated by Django 3.1.3 on 2020-11-23 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201123_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_item',
            name='album',
        ),
        migrations.AddField(
            model_name='gallery_item',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='gallery.album', verbose_name='альбом'),
            preserve_default=False,
        ),
    ]
