# Generated by Django 3.1.3 on 2021-07-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL, verbose_name='Понравился этот коментарий')),
                ('publication_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='publications.publication', verbose_name='Публикация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='от кого')),
            ],
        ),
    ]
