# Generated by Django 3.1.2 on 2020-11-13 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_to_comment_like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment_to_comment_like',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL, verbose_name='Какому комментарию'),
        ),
        migrations.AddField(
            model_name='comment_to_comment',
            name='likes',
            field=models.ManyToManyField(related_name='comment_to_comment_like', to=settings.AUTH_USER_MODEL, verbose_name='Какому комментарию'),
        ),
        migrations.DeleteModel(
            name='Comment_like',
        ),
        migrations.DeleteModel(
            name='Comment_to_comment_like',
        ),
    ]
