# Generated by Django 3.1.3 on 2021-07-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications', verbose_name='Фото')),
                ('views', models.IntegerField(default=0)),
                ('avialable', models.BooleanField(default=True, verbose_name='Есть в наличии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='понравилось')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
    ]
