# Generated by Django 3.1.2 on 2020-10-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='avialable',
            field=models.BooleanField(default=True, verbose_name='Есть в наличии'),
        ),
    ]
