# Generated by Django 3.1.2 on 2020-11-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20201115_1949'),
        ('publications', '0004_auto_20201112_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='core.profile', verbose_name='владелец'),
        ),
    ]
